FROM openanalytics/r-base
LABEL maintainer="candrews@usgs.com"

RUN export DEBIAN_FRONTEND=noninteractive; apt-get -y update \
  && apt-get install -y libssl-dev  \
  libxml2-dev \
  libgdal-dev \
  libproj-dev \
  gdal-bin

RUN ["install2.r", "fastmatch", "iotools", "iotools", "Hmisc", "data.table", "gridExtra", "RColorBrewer", "Rcpp", "forcats", "Rcpp", "raster", "leaflet", "circular", "RSQLite", "rgdal", "rgeos", "ncdf4", "RCurl", "sp", "maps", "maptools", "shinydashboard", "httr", "hexbin", "rmarkdown", "zoo"]

RUN ["install2.r", "tidyverse"]
RUN R -e "install.packages(c('shiny', 'rmarkdown'), repos='https://cloud.r-project.org/')"

RUN mkdir /root/LTDV
COPY . /root/LTDV/

RUN R CMD INSTALL /root/LTDV/Packages/htmlwidgets
RUN R CMD INSTALL --library= /usr/lib64/R/library /root/LTDV/Packages/plotly
RUN R -e 'install.packages("/root/LTDV/Packages/rSW2utils.tar.gz", repos = NULL, type = "source")'
RUN R CMD INSTALL /root/LTDV/Packages/rSOILWAT2
RUN R CMD INSTALL /root/LTDV/Packages/rSFSW2

COPY Rprofile.site /usr/lib/R/etc/

EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/root/LTDV/shiny-app')"]
